update countries set mnemo = trim(' AD  ') where country=trim(' Андорра ');
update countries set mnemo = trim(' AE  ') where country=trim(' Объединенные Арабские Эмираты ');
update countries set mnemo = trim(' AF  ') where country=trim(' Афганистан  ');
update countries set mnemo = trim(' AG  ') where country=trim(' Антигуа и Барбуда ');
update countries set mnemo = trim(' AI  ') where country=trim(' Антилья ');
update countries set mnemo = trim(' AL  ') where country=trim(' Албания ');
update countries set mnemo = trim(' АM  ') where country=trim(' Армения ');
update countries set mnemo = trim(' AN  ') where country=trim(' Нидерландские Антиллы ');
update countries set mnemo = trim(' AO  ') where country=trim(' Ангола  ');
update countries set mnemo = trim(' AP  ') where country=trim(' Африканская региональная организация промышленной собственности ');
update countries set mnemo = trim(' AR  ') where country=trim(' Аргентина ');
update countries set mnemo = trim(' АS  ') where country=trim(' Американские Самоа  ');
update countries set mnemo = trim(' AT  ') where country=trim(' Австрия ');
update countries set mnemo = trim(' AU  ') where country=trim(' Австралия ');
update countries set mnemo = trim(' AW  ') where country=trim(' Аруба ');
update countries set mnemo = trim(' AZ  ') where country=trim(' Азербайджан ');
update countries set mnemo = trim(' BA  ') where country=trim(' Босния и Герцеговина  ');
update countries set mnemo = trim(' BB  ') where country=trim(' Барбадос  ');
update countries set mnemo = trim(' BD  ') where country=trim(' Бангладеш ');
update countries set mnemo = trim(' BE  ') where country=trim(' Бельгия ');
update countries set mnemo = trim(' BF  ') where country=trim(' Буркина Фасо  ');
update countries set mnemo = trim(' BG  ') where country=trim(' Болгария  ');
update countries set mnemo = trim(' BH  ') where country=trim(' Бахрейн ');
update countries set mnemo = trim(' BI  ') where country=trim(' Бурунди ');
update countries set mnemo = trim(' BJ  ') where country=trim(' Бенин ');
update countries set mnemo = trim(' BM  ') where country=trim(' Бермуды ');
update countries set mnemo = trim(' BN  ') where country=trim(' Бруней Даруссалам ');
update countries set mnemo = trim(' BO  ') where country=trim(' Боливия ');
update countries set mnemo = trim(' BR  ') where country=trim(' Бразилия  ');
update countries set mnemo = trim(' BS  ') where country=trim(' Багамы  ');
update countries set mnemo = trim(' BT  ') where country=trim(' Бутан ');
update countries set mnemo = trim(' BV  ') where country=trim(' Буве, о.  ');
update countries set mnemo = trim(' BW  ') where country=trim(' Ботсвана  ');
update countries set mnemo = trim(' BX  ') where country=trim(' Ведомство Бенилюкс по товарным знакам и промышленным образцам ');
update countries set mnemo = trim(' BY  ') where country=trim(' Беларусь  ');
update countries set mnemo = trim(' BZ  ') where country=trim(' Белиз ');
update countries set mnemo = trim(' CA  ') where country=trim(' Канада  ');
update countries set mnemo = trim(' CD  ') where country=trim(' Демократическая Республика Конго  ');
update countries set mnemo = trim(' CF  ') where country=trim(' Центрально-Африканская Республика ');
update countries set mnemo = trim(' CG  ') where country=trim(' Конго ');
update countries set mnemo = trim(' CH  ') where country=trim(' Швейцария ');
update countries set mnemo = trim(' CI  ') where country=trim(' Берег Слоновой Кости  ');
update countries set mnemo = trim(' CK  ') where country=trim(' Острова Кука  ');
update countries set mnemo = trim(' CL  ') where country=trim(' Чили  ');
update countries set mnemo = trim(' CM  ') where country=trim(' Камерун ');
update countries set mnemo = trim(' CN  ') where country=trim(' Китай ');
update countries set mnemo = trim(' CO  ') where country=trim(' Колумбия  ');
update countries set mnemo = trim(' CR  ') where country=trim(' Коста Рика  ');
update countries set mnemo = trim(' CU  ') where country=trim(' Куба  ');
update countries set mnemo = trim(' CV  ') where country=trim(' Зеленый Мыс ');
update countries set mnemo = trim(' CY  ') where country=trim(' Кипр  ');
update countries set mnemo = trim(' CZ  ') where country=trim(' Чешская Республика  ');
update countries set mnemo = trim(' DE  ') where country=trim(' Германия  ');
update countries set mnemo = trim(' DJ  ') where country=trim(' Джибути ');
update countries set mnemo = trim(' DK  ') where country=trim(' Дания ');
update countries set mnemo = trim(' DM  ') where country=trim(' Доминика  ');
update countries set mnemo = trim(' DO  ') where country=trim(' Доминиканская Республика  ');
update countries set mnemo = trim(' DZ  ') where country=trim(' Алжир ');
update countries set mnemo = trim(' EA  ') where country=trim(' Евразийская патентная организация ');
update countries set mnemo = trim(' EC  ') where country=trim(' Эквадор ');
update countries set mnemo = trim(' EE  ') where country=trim(' Эстония ');
update countries set mnemo = trim(' EG  ') where country=trim(' Египет  ');
update countries set mnemo = trim(' EH  ') where country=trim(' Западная Сахара ');
update countries set mnemo = trim(' EM  ') where country=trim(' Ведомство по гармонизации на внутреннем рынке (товарные знаки и промышленные образцы) ');
update countries set mnemo = trim(' EP  ') where country=trim(' Европейское патентное ведомство ');
update countries set mnemo = trim(' ER  ') where country=trim(' Эритрея ');
update countries set mnemo = trim(' ES  ') where country=trim(' Испания ');
update countries set mnemo = trim(' ET  ') where country=trim(' Эфиопия ');
update countries set mnemo = trim(' FI  ') where country=trim(' Финляндия ');
update countries set mnemo = trim(' FJ  ') where country=trim(' Фиджи ');
update countries set mnemo = trim(' FK  ') where country=trim(' Фолклендские Острова  ');
update countries set mnemo = trim(' FM  ') where country=trim(' Микронезия  ');
update countries set mnemo = trim(' FO  ') where country=trim(' Фарерские Острова ');
update countries set mnemo = trim(' FR  ') where country=trim(' Франция ');
update countries set mnemo = trim(' GA  ') where country=trim(' Габон ');
update countries set mnemo = trim(' GB  ') where country=trim(' Великобритания  ');
update countries set mnemo = trim(' GD  ') where country=trim(' Гренада ');
update countries set mnemo = trim(' GE  ') where country=trim(' Грузия  ');
update countries set mnemo = trim(' GH  ') where country=trim(' Гана  ');
update countries set mnemo = trim(' GI  ') where country=trim(' Гибралтар ');
update countries set mnemo = trim(' GL  ') where country=trim(' Гренландия  ');
update countries set mnemo = trim(' GM  ') where country=trim(' Гамбия  ');
update countries set mnemo = trim(' GN  ') where country=trim(' Гвинея  ');
update countries set mnemo = trim(' GQ  ') where country=trim(' Экваториальная Гвинея ');
update countries set mnemo = trim(' GR  ') where country=trim(' Греция  ');
update countries set mnemo = trim(' GS  ') where country=trim(' Южная Джорджия и Южные Сандвичевы ');
update countries set mnemo = trim(' GT  ') where country=trim(' Гватемала ');
update countries set mnemo = trim(' GW  ') where country=trim(' Гвинея-Биссау ');
update countries set mnemo = trim(' GY  ') where country=trim(' Гайяна  ');
update countries set mnemo = trim(' HN  ') where country=trim(' Гондурас  ');
update countries set mnemo = trim(' HR  ') where country=trim(' Хорватия  ');
update countries set mnemo = trim(' HT  ') where country=trim(' Гаити ');
update countries set mnemo = trim(' HU  ') where country=trim(' Венгрия ');
update countries set mnemo = trim(' IB  ') where country=trim(' Международное бюро Всемирной организации интеллектуальной собственности ');
update countries set mnemo = trim(' ID  ') where country=trim(' Индонезия ');
update countries set mnemo = trim(' IE  ') where country=trim(' Ирландия  ');
update countries set mnemo = trim(' IL  ') where country=trim(' Израиль ');
update countries set mnemo = trim(' IN  ') where country=trim(' Индия ');
update countries set mnemo = trim(' IQ  ') where country=trim(' Ирак  ');
update countries set mnemo = trim(' IR  ') where country=trim(' Иран  ');
update countries set mnemo = trim(' IS  ') where country=trim(' Исландия  ');
update countries set mnemo = trim(' IT  ') where country=trim(' Италия  ');
update countries set mnemo = trim(' JM  ') where country=trim(' Ямайка  ');
update countries set mnemo = trim(' JO  ') where country=trim(' Иордания  ');
update countries set mnemo = trim(' JP  ') where country=trim(' Япония  ');
update countries set mnemo = trim(' KE  ') where country=trim(' Кения ');
update countries set mnemo = trim(' KG  ') where country=trim(' Кыргызстан  ');
update countries set mnemo = trim(' KH  ') where country=trim(' Камбоджа  ');
update countries set mnemo = trim(' KI  ') where country=trim(' Кирибати  ');
update countries set mnemo = trim(' KM  ') where country=trim(' Коморы  ');
update countries set mnemo = trim(' KN  ') where country=trim(' Сент-Китс и Невис ');
update countries set mnemo = trim(' KP  ') where country=trim(' Корейская Народно-Демократическая Республика  ');
update countries set mnemo = trim(' KR  ') where country=trim(' Республика Корея  ');
update countries set mnemo = trim(' KW  ') where country=trim(' Кувейт  ');
update countries set mnemo = trim(' KY  ') where country=trim(' Каймановы Острова ');
update countries set mnemo = trim(' KZ  ') where country=trim(' Казахстан ');
update countries set mnemo = trim(' LA  ') where country=trim(' Лаос  ');
update countries set mnemo = trim(' LB  ') where country=trim(' Ливан ');
update countries set mnemo = trim(' LC  ') where country=trim(' Сент-Люсия  ');
update countries set mnemo = trim(' LI  ') where country=trim(' Лихтенштейн ');
update countries set mnemo = trim(' LK  ') where country=trim(' Шри-Ланка ');
update countries set mnemo = trim(' LR  ') where country=trim(' Либерия ');
update countries set mnemo = trim(' LS  ') where country=trim(' Лесото  ');
update countries set mnemo = trim(' LT  ') where country=trim(' Литва ');
update countries set mnemo = trim(' LU  ') where country=trim(' Люксембург  ');
update countries set mnemo = trim(' LV  ') where country=trim(' Латвия  ');
update countries set mnemo = trim(' LY  ') where country=trim(' Ливия ');
update countries set mnemo = trim(' MA  ') where country=trim(' Марокко ');
update countries set mnemo = trim(' MC  ') where country=trim(' Монако  ');
update countries set mnemo = trim(' MD  ') where country=trim(' Республика Молдова  ');
update countries set mnemo = trim(' MG  ') where country=trim(' Мадагаскар  ');
update countries set mnemo = trim(' MH  ') where country=trim(' Маршалловы Острова  ');
update countries set mnemo = trim(' MK  ') where country=trim(' Бывшая Югославская Республика Македония ');
update countries set mnemo = trim(' ML  ') where country=trim(' Мали  ');
update countries set mnemo = trim(' MM  ') where country=trim(' Мианмар ');
update countries set mnemo = trim(' MN  ') where country=trim(' Монголия  ');
update countries set mnemo = trim(' MO  ') where country=trim(' Макау ');
update countries set mnemo = trim(' MP  ') where country=trim(' Северные Марианские Острова ');
update countries set mnemo = trim(' MR  ') where country=trim(' Мавритания  ');
update countries set mnemo = trim(' MS  ') where country=trim(' Монтсеррат  ');
update countries set mnemo = trim(' MT  ') where country=trim(' Мальта  ');
update countries set mnemo = trim(' MU  ') where country=trim(' Маврикий  ');
update countries set mnemo = trim(' MV  ') where country=trim(' Мальдивы  ');
update countries set mnemo = trim(' MW  ') where country=trim(' Малави  ');
update countries set mnemo = trim(' MX  ') where country=trim(' Мексика ');
update countries set mnemo = trim(' MY  ') where country=trim(' Малайзия  ');
update countries set mnemo = trim('   ') where country=trim('   ');
update countries set mnemo = trim(' MZ  ') where country=trim(' Мозамбик  ');
update countries set mnemo = trim(' NA  ') where country=trim(' Намибия ');
update countries set mnemo = trim(' NE  ') where country=trim(' Нигер ');
update countries set mnemo = trim(' NG  ') where country=trim(' Нигерия ');
update countries set mnemo = trim(' NI  ') where country=trim(' Никарагуа ');
update countries set mnemo = trim(' NL  ') where country=trim(' Нидерланды  ');
update countries set mnemo = trim(' NO  ') where country=trim(' Норвегия  ');
update countries set mnemo = trim(' NP  ') where country=trim(' Непал ');
update countries set mnemo = trim(' NR  ') where country=trim(' Науру ');
update countries set mnemo = trim(' NZ  ') where country=trim(' Новая Зеландия  ');
update countries set mnemo = trim(' OA  ') where country=trim(' Африканская организация интеллектуальной собственности  ');
update countries set mnemo = trim(' OM  ') where country=trim(' Оман  ');
update countries set mnemo = trim(' PA  ') where country=trim(' Панама  ');
update countries set mnemo = trim(' PE  ') where country=trim(' Перу  ');
update countries set mnemo = trim(' PG  ') where country=trim(' Папуа-Новая Гвинея  ');
update countries set mnemo = trim(' PH  ') where country=trim(' Филиппины ');
update countries set mnemo = trim(' PK  ') where country=trim(' Пакистан  ');
update countries set mnemo = trim(' PL  ') where country=trim(' Польша  ');
update countries set mnemo = trim(' PT  ') where country=trim(' Португалия  ');
update countries set mnemo = trim(' PW  ') where country=trim(' Палау ');
update countries set mnemo = trim(' PY  ') where country=trim(' Парагвай  ');
update countries set mnemo = trim(' QA  ') where country=trim(' Катар ');
update countries set mnemo = trim(' RO  ') where country=trim(' Румыния ');
update countries set mnemo = trim(' RU  ') where country=trim(' Российская Федерация  ');
update countries set mnemo = trim(' RW  ') where country=trim(' Руанда  ');
update countries set mnemo = trim(' SA  ') where country=trim(' Саудовская Аравия ');
update countries set mnemo = trim(' SB  ') where country=trim(' Соломоновы Острова  ');
update countries set mnemo = trim(' SC  ') where country=trim(' Сейшелы ');
update countries set mnemo = trim(' SD  ') where country=trim(' Судан ');
update countries set mnemo = trim(' SE  ') where country=trim(' Швеция  ');
update countries set mnemo = trim(' SG  ') where country=trim(' Сингапур  ');
update countries set mnemo = trim(' SH  ') where country=trim(' Святая Елена  ');
update countries set mnemo = trim(' SI  ') where country=trim(' Словения  ');
update countries set mnemo = trim(' SK  ') where country=trim(' Словакия  ');
update countries set mnemo = trim(' SL  ') where country=trim(' Сьерра-Леоне  ');
update countries set mnemo = trim(' SM  ') where country=trim(' Сан-Марино  ');
update countries set mnemo = trim(' SN  ') where country=trim(' Сенегал ');
update countries set mnemo = trim(' SO  ') where country=trim(' Сомали  ');
update countries set mnemo = trim(' SR  ') where country=trim(' Суринам ');
update countries set mnemo = trim(' ST  ') where country=trim(' Сан-Томе и Принсипи ');
update countries set mnemo = trim(' SV  ') where country=trim(' Эль-Сальвадор ');
update countries set mnemo = trim(' SY  ') where country=trim(' Сирия ');
update countries set mnemo = trim(' SZ  ') where country=trim(' Свазиленд ');
update countries set mnemo = trim(' TC  ') where country=trim(' Турецкие и Кайкосские Острова ');
update countries set mnemo = trim(' TD  ') where country=trim(' Чад ');
update countries set mnemo = trim(' TG  ') where country=trim(' Того  ');
update countries set mnemo = trim(' TH  ') where country=trim(' Таиланд ');
update countries set mnemo = trim(' TJ  ') where country=trim(' Таджикистан ');
update countries set mnemo = trim(' TM  ') where country=trim(' Туркменистан  ');
update countries set mnemo = trim(' TN  ') where country=trim(' Тунис ');
update countries set mnemo = trim(' TO  ') where country=trim(' Тонга ');
update countries set mnemo = trim(' TP  ') where country=trim(' Восточный Тимор ');
update countries set mnemo = trim(' TR  ') where country=trim(' Турция  ');
update countries set mnemo = trim(' TT  ') where country=trim(' Тринидад и Тобаго ');
update countries set mnemo = trim(' TV  ') where country=trim(' Тувалу  ');
update countries set mnemo = trim(' TW  ') where country=trim(' Тайвань, провинция Китая  ');
update countries set mnemo = trim(' TZ  ') where country=trim(' Объединенная Республика Танзания  ');
update countries set mnemo = trim(' UA  ') where country=trim(' Украина ');
update countries set mnemo = trim(' UG  ') where country=trim(' Уганда  ');
update countries set mnemo = trim(' US  ') where country=trim(' Соединенные Штаты Америки ');
update countries set mnemo = trim(' UY  ') where country=trim(' Уругвай ');
update countries set mnemo = trim(' UZ  ') where country=trim(' Узбекистан  ');
update countries set mnemo = trim(' VA  ') where country=trim(' Ватикан ');
update countries set mnemo = trim(' VC  ') where country=trim(' Сент-Винсент и Гренадины  ');
update countries set mnemo = trim(' VE  ') where country=trim(' Венесуэла ');
update countries set mnemo = trim(' VG  ') where country=trim(' Виргинские Острова  ');
update countries set mnemo = trim(' VN  ') where country=trim(' Вьетнам ');
update countries set mnemo = trim(' VU  ') where country=trim(' Вануату ');
update countries set mnemo = trim(' WO  ') where country=trim(' Всемирная организация интеллектуальной собственности  ');
update countries set mnemo = trim(' WS  ') where country=trim(' Самоа ');
update countries set mnemo = trim(' YE  ') where country=trim(' Йемен ');
update countries set mnemo = trim(' YU  ') where country=trim(' Югославия ');
update countries set mnemo = trim(' ZA  ') where country=trim(' Южная Африка  ');
update countries set mnemo = trim(' ZM  ') where country=trim(' Замбия  ');
update countries set mnemo = trim(' ZR  ') where country=trim(' Заир  ');
update countries set mnemo = trim(' ZW  ') where country=trim(' Зимбабве  ');

