insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),499,trim('Килограмм в секунду'),trim('  кг/с    '),trim('      '),trim('  КГ/С    '),trim('  KGS '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   533 ,trim('    Тонна пара в час    '),trim('  т пар/ч '),trim('      '),trim('  Т ПАР/Ч '),trim('  TSH '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   596 ,trim('    Кубический метр в секунду   '),trim('  м3/с    '),trim('  m3/s    '),trim('  М3/С    '),trim('  MQS '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   598 ,trim('    Кубический метр в час   '),trim('  м3/ч    '),trim('  m3/h    '),trim('  М3/Ч    '),trim('  MQH '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   599 ,trim('    Тысяча кубических метров в сутки    '),trim('  103м3/сут   '),trim('      '),trim('  ТЫС М3/СУТ  '),trim('  TQD '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   616 ,trim('    Бобина  '),trim('  боб '),trim('      '),trim('  БОБ '),trim('  NBB '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   625 ,trim('    Лист    '),trim('  л.  '),trim('      '),trim('  ЛИСТ    '),trim('  LEF '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   626 ,trim('    Сто листов  '),trim('  100 л.  '),trim('      '),trim('  100 ЛИСТ    '),trim('  CLF '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   630 ,trim('    Тысяча стандартных условных кирпичей    '),trim('  тыс станд. усл. кирп    '),trim('      '),trim('  ТЫС СТАНД УСЛ КИРП  '),trim('  MBE '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   641 ,trim('    Дюжина (12 шт.) '),trim('  дюжина  '),trim('  Doz; 12 '),trim('  ДЮЖИНА  '),trim('  DZN '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   657 ,trim('    Изделие '),trim('  изд '),trim('      '),trim('  ИЗД '),trim('  NAR '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   683 ,trim('    Сто ящиков  '),trim('  100 ящ. '),trim('  Hbx '),trim('  100 ЯЩ  '),trim('  HBX '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   704 ,trim('    Набор   '),trim('  набор   '),trim('      '),trim('  НАБОР   '),trim('  SET '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   715 ,trim('    Пара (2 шт.)    '),trim('  пар '),trim('  pr; 2   '),trim('  ПАР '),trim('  NPR '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   730 ,trim('    Два десятка '),trim('  20  '),trim('  20  '),trim('  2 ДЕС   '),trim('  SCO '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   732 ,trim('    Десять пар  '),trim('  10 пар  '),trim('      '),trim('  ДЕС ПАР '),trim('  TPR '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   733 ,trim('    Дюжина пар  '),trim('  дюжина пар  '),trim('      '),trim('  ДЮЖИНА ПАР  '),trim('  DPR '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   734 ,trim('    Посылка '),trim('  посыл   '),trim('      '),trim('  ПОСЫЛ   '),trim('  NPL '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   735 ,trim('    Часть   '),trim('  часть   '),trim('      '),trim('  ЧАСТЬ   '),trim('  NPT '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   736 ,trim('    Рулон   '),trim('  рул '),trim('      '),trim('  РУЛ '),trim('  NPL '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   737 ,trim('    Дюжина рулонов  '),trim('  дюжина рул  '),trim('      '),trim('  ДЮЖИНА РУЛ  '),trim('  DRL '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   740 ,trim('    Дюжина штук '),trim('  дюжина шт   '),trim('      '),trim('  ДЮЖИНА ШТ   '),trim('  DPC '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   745 ,trim('    Элемент '),trim('  элем    '),trim('  CI  '),trim('  ЭЛЕМ    '),trim('  NCL '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   778 ,trim('    Упаковка    '),trim('  упак    '),trim('      '),trim('  УПАК    '),trim('  NMP '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   780 ,trim('    Дюжина упаковок '),trim('  дюжина упак '),trim('      '),trim('  ДЮЖИНА УПАК '),trim('  DZP '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   781 ,trim('    Сто упаковок    '),trim('  100 упак    '),trim('      '),trim('  100 УПАК    '),trim('  CNP '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   796 ,trim('    Штука   '),trim('  шт  '),trim('  pc; 1   '),trim('  ШТ  '),trim('  PCE; NMB    '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   797 ,trim('    Сто штук    '),trim('  100 шт  '),trim('  100 '),trim('  100 ШТ  '),trim('  CEN '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   798 ,trim('    Тысяча штук '),trim('  тыс. шт; 1000 шт    '),trim('  1000    '),trim('  ТЫС ШТ  '),trim('  MIL '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   798 ,trim('    Миллион штук    '),trim('  106шт   '),trim('  106 '),trim('  МЛН ШТ  '),trim('  MIO '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   800 ,trim('    Миллиард штук   '),trim('  109шт   '),trim('  109 '),trim('  МЛРД ШТ '),trim('  MLD '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   801 ,trim('    Биллион штук (Европа);  '),trim('  1012шт  '),trim('  1012    '),trim('  БИЛЛ ШТ (ЕВР);  '),trim('  BIL '));
--insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),       ,trim('    триллион штук   '),trim('      '),trim('      '),trim('  ТРИЛЛ ШТ    '),trim('      '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   802 ,trim('    Квинтильон штук (Европа)    '),trim('  1018шт  '),trim('  1018    '),trim('  КВИНТ ШТ    '),trim('  TRL '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   820 ,trim('    Крепость спирта по массе    '),trim('  креп. спирта по массе   '),trim('  % mds   '),trim('  КРЕП СПИРТ ПО МАССЕ '),trim('  ASM '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   821 ,trim('    Крепость спирта по объему   '),trim('  креп. спирта по объему  '),trim('  % vol   '),trim('  КРЕП СПИРТ ПО ОБЪЕМ '),trim('  ASV '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   831 ,trim('    Литр чистого (100%) спирта  '),trim('  л 100% спирта   '),trim('      '),trim('  Л ЧИСТ СПИРТ    '),trim('  LPA '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   833 ,trim('    Гектолитр чистого (100%) спирта '),trim('  Гл 100% спирта  '),trim('      '),trim('  ГЛ ЧИСТ СПИРТ   '),trim('  HPA '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   841 ,trim('    Килограмм пероксида водорода    '),trim('  кг H2О2 '),trim('      '),trim('  КГ ПЕРОКСИД ВОДОРОДА    '),trim('  -   '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   845 ,trim('    Килограмм 90%-го сухого вещества    '),trim('  кг 90% с/в  '),trim('      '),trim('  КГ 90 ПРОЦ СУХ ВЕЩ  '),trim('  KSD '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   847 ,trim('    Тонна 90%-го сухого вещества    '),trim('  т 90% с/в   '),trim('      '),trim('  Т 90 ПРОЦ СУХ ВЕЩ   '),trim('  TSD '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   852 ,trim('    Килограмм оксида калия  '),trim('  кг К2О  '),trim('      '),trim('  КГ ОКСИД КАЛИЯ  '),trim('  KPO '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   859 ,trim('    Килограмм гидроксида калия  '),trim('  кг КОН  '),trim('      '),trim('  КГ ГИДРОКСИД КАЛИЯ  '),trim('  KPH '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   861 ,trim('    Килограмм азота '),trim('  кг N    '),trim('      '),trim('  КГ АЗОТ '),trim('  KNI '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   863 ,trim('    Килограмм гидроксида натрия '),trim('  кг NaOH '),trim('      '),trim('  КГ ГИДРОКСИД НАТРИЯ '),trim('  KSH '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   865 ,trim('    Килограмм пятиокиси фосфора '),trim('  кг Р2О5 '),trim('      '),trim('  КГ ПЯТИОКИСЬ    '),trim('  KPP '));
insert into nsi_units values(get_office_unique('UNIVERSAL_ID'),   867 ,trim('    Килограмм урана '),trim('  кг U    '),trim('      '),trim('  КГ УРАН '),trim('  KUR '));

