-- Start of DDL Script for Sequence CREATOR.ORDERS_ID_ORDERS_FORMULA
-- Generated 05.05.2012 19:41:18 from CREATOR@STARNEW

CREATE SEQUENCE orders_id_orders_formula
  INCREMENT BY 1
  START WITH 19
  MINVALUE 1
  MAXVALUE 999
  NOCYCLE
  NOORDER
  NOCACHE
/


-- End of DDL Script for Sequence CREATOR.ORDERS_ID_ORDERS_FORMULA

