-- Start of DDL Script for User CREATOR
-- Generated 29.09.2011 0:48:59 from CREATOR@STARREG

-- Drop the old instance of CREATOR
DROP USER creator
  CASCADE
/

CREATE USER creator
IDENTIFIED BY "123456"
DEFAULT TABLESPACE STARLIGHT_T
TEMPORARY TABLESPACE TEMP
/
GRANT ALTER ANY ROLE TO creator
/
GRANT ALTER USER TO creator
/
GRANT CREATE USER TO creator
/
GRANT DELETE ANY TABLE TO creator
/
GRANT DROP USER TO creator
/
GRANT EXECUTE ANY PROCEDURE TO creator
/
GRANT GRANT ANY ROLE TO creator
/
GRANT INSERT ANY TABLE TO creator
/
GRANT SELECT ANY DICTIONARY TO creator
/
GRANT SELECT ANY SEQUENCE TO creator
/
GRANT SELECT ANY TABLE TO creator
/
GRANT UNLIMITED TABLESPACE TO creator
/
GRANT UPDATE ANY TABLE TO creator
/
GRANT CONNECT TO creator
/
GRANT DBA TO creator
/
GRANT MGMT_USER TO creator
/
GRANT NEW_ROLE TO creator
/
ALTER USER creator DEFAULT ROLE ALL
/


-- End of DDL Script for User CREATOR

