-- Start of DDL Script for Role NEW_ROLE
-- Generated 29.09.2011 0:49:19 from CREATOR@STARREG

-- Drop the old instance of NEW_ROLE
DROP ROLE new_role
/

CREATE ROLE new_role
NOT IDENTIFIED
/
GRANT EXECUTE ANY PROCEDURE TO new_role
/
GRANT SELECT ANY SEQUENCE TO new_role
/
GRANT SELECT ANY TABLE TO new_role
/
GRANT CONNECT TO new_role
/
GRANT DBA TO new_role
/
GRANT RESOURCE TO new_role
/
GRANT UPDATE ON CREATOR.ADMIN_EMPLOYEES_ROLE_GROUPS TO new_role
/
GRANT SELECT ON CREATOR.ADMIN_EMPLOYEES_ROLE_GROUPS TO new_role
/
GRANT INSERT ON CREATOR.ADMIN_EMPLOYEES_ROLE_GROUPS TO new_role
/
GRANT UPDATE ON CREATOR.ADMIN_PROGRAMS TO new_role
/
GRANT INSERT ON CREATOR.ADMIN_PROGRAMS TO new_role
/
GRANT SELECT ON CREATOR.ADMIN_PROGRAMS TO new_role
/
GRANT SELECT ON CREATOR.ADMIN_PROGRAMS_ROLE_GROUPS TO new_role
/
GRANT UPDATE ON CREATOR.ADMIN_PROGRAMS_ROLE_GROUPS TO new_role
/
GRANT INSERT ON CREATOR.ADMIN_PROGRAMS_ROLE_GROUPS TO new_role
/
GRANT INSERT ON CREATOR.ADMIN_ROLE_GROUPS TO new_role
/
GRANT SELECT ON CREATOR.ADMIN_ROLE_GROUPS TO new_role
/
GRANT UPDATE ON CREATOR.ADMIN_ROLE_GROUPS TO new_role
/
GRANT EXECUTE ON CREATOR.BOOKS TO new_role
/
GRANT UPDATE ON CREATOR.BOOKS_ADVERTISMENTS TO new_role
/
GRANT SELECT ON CREATOR.BOOKS_ADVERTISMENTS TO new_role
/
GRANT INSERT ON CREATOR.BOOKS_CLIENT_TYPES TO new_role
/
GRANT UPDATE ON CREATOR.BOOKS_CLIENT_TYPES TO new_role
/
GRANT SELECT ON CREATOR.BOOKS_CLIENT_TYPES TO new_role
/
GRANT INSERT ON CREATOR.BOOKS_DEPARTMENTS TO new_role
/
GRANT UPDATE ON CREATOR.BOOKS_DEPARTMENTS TO new_role
/
GRANT SELECT ON CREATOR.BOOKS_DEPARTMENTS TO new_role
/
GRANT INSERT ON CREATOR.BOOKS_JOB_TITLES TO new_role
/
GRANT SELECT ON CREATOR.BOOKS_JOB_TITLES TO new_role
/
GRANT UPDATE ON CREATOR.BOOKS_JOB_TITLES TO new_role
/
GRANT UPDATE ON CREATOR.BOOKS_REGIONS TO new_role
/
GRANT SELECT ON CREATOR.BOOKS_REGIONS TO new_role
/
GRANT INSERT ON CREATOR.BOOKS_REGIONS TO new_role
/
GRANT INSERT ON CREATOR.CLIENTS TO new_role
/
GRANT SELECT ON CREATOR.CLIENTS TO new_role
/
GRANT UPDATE ON CREATOR.CLIENTS TO new_role
/
GRANT UPDATE ON CREATOR.CLIENTS_GROUPS TO new_role
/
GRANT SELECT ON CREATOR.CLIENTS_GROUPS TO new_role
/
GRANT INSERT ON CREATOR.CLIENTS_GROUPS TO new_role
/
GRANT DELETE ON CREATOR.CLIENTS_GROUPS TO new_role
/
GRANT SELECT ON CREATOR.CLIENTS_ID TO new_role
/
GRANT SELECT ON CREATOR.CLIENTS_ID_GROUPS TO new_role
/
GRANT EXECUTE ON CREATOR.CLIENTS_PKG TO new_role
/
GRANT UPDATE ON CREATOR.CLIENTS_PRINT TO new_role
/
GRANT INSERT ON CREATOR.CLIENTS_PRINT TO new_role
/
GRANT SELECT ON CREATOR.CLIENTS_PRINT TO new_role
/
GRANT SELECT ON CREATOR.CLIENTS_SALES TO new_role
/
GRANT UPDATE ON CREATOR.CLIENTS_SALES TO new_role
/
GRANT INSERT ON CREATOR.CLIENTS_SALES TO new_role
/
GRANT SELECT ON CREATOR.CLIENTS_VIEW2 TO new_role
/
GRANT SELECT ON CREATOR.CLIENT_DEBT TO new_role
/
GRANT UPDATE ON CREATOR.CLIENT_DEBT TO new_role
/
GRANT INSERT ON CREATOR.CLIENT_DEBT TO new_role
/
GRANT SELECT ON CREATOR.CLIENT_SALES TO new_role
/
GRANT EXECUTE ON CREATOR.CONST_OFFICE TO new_role
/
GRANT EXECUTE ON CREATOR.CONST_PICTURE_PATH TO new_role
/
GRANT INSERT ON CREATOR.CURRENCY TO new_role
/
GRANT SELECT ON CREATOR.CURRENCY TO new_role
/
GRANT UPDATE ON CREATOR.CURRENCY TO new_role
/
GRANT SELECT ON CREATOR.DEBETORS TO new_role
/
GRANT INSERT ON CREATOR.DEBETORS TO new_role
/
GRANT UPDATE ON CREATOR.DEBETORS TO new_role
/
GRANT EXECUTE ON CREATOR.DICTS TO new_role
/
GRANT INSERT ON CREATOR.EMPLOYEES_DEPARTMENTS TO new_role
/
GRANT SELECT ON CREATOR.EMPLOYEES_DEPARTMENTS TO new_role
/
GRANT UPDATE ON CREATOR.EMPLOYEES_DEPARTMENTS TO new_role
/
GRANT UPDATE ON CREATOR.EMPLOYEES_JOB_TITLES TO new_role
/
GRANT INSERT ON CREATOR.EMPLOYEES_JOB_TITLES TO new_role
/
GRANT SELECT ON CREATOR.EMPLOYEES_JOB_TITLES TO new_role
/
GRANT SELECT ON CREATOR.EMPLOYEES_VIEW TO new_role
/
GRANT UPDATE ON CREATOR.ERR_LOGS TO new_role
/
GRANT INSERT ON CREATOR.ERR_LOGS TO new_role
/
GRANT SELECT ON CREATOR.ERR_LOGS TO new_role
/
GRANT EXECUTE ON CREATOR.GET_OFFICE_UNIQUE TO new_role
/
GRANT SELECT ON CREATOR.SEQ_COURSES TO new_role
/
GRANT EXECUTE ON CREATOR.STARTER TO new_role
/
GRANT SELECT ON SYS.BIN$3xB64ib3RGOxnl0hLBF06w==$0 TO new_role
/
GRANT INSERT ON SYS.BIN$3xB64ib3RGOxnl0hLBF06w==$0 TO new_role
/
GRANT UPDATE ON SYS.BIN$3xB64ib3RGOxnl0hLBF06w==$0 TO new_role
/
GRANT INSERT ON SYS.BIN$ARGxjJi9QsKtwE92UmuU5Q==$0 TO new_role
/
GRANT SELECT ON SYS.BIN$ARGxjJi9QsKtwE92UmuU5Q==$0 TO new_role
/
GRANT UPDATE ON SYS.BIN$ARGxjJi9QsKtwE92UmuU5Q==$0 TO new_role
/


-- End of DDL Script for Role NEW_ROLE

