CREATE TABLESPACE "STARLIGHT_T" DATAFILE 'D:\ORACLE\PRODUCT\10.2.0\ORADATA\STARREG\STARLIGHT_T.DBF' SIZE 100M
AUTOEXTEND ON NEXT 200M MAXSIZE 1024M
DEFAULT STORAGE (INITIAL 10M NEXT 1M PCTINCREASE 10)
PERMANENT
ONLINE
LOGGING;

ALTER DATABASE DEFAULT TABLESPACE "STARLIGHT_T";

CREATE TABLESPACE "STARLIGHT_I" DATAFILE 'D:\ORACLE\PRODUCT\10.2.0\ORADATA\STARREG\STARLIGHT_I.DBF' SIZE 100M
AUTOEXTEND ON NEXT 200M MAXSIZE 1024M
DEFAULT STORAGE (INITIAL 10M NEXT 1M PCTINCREASE 10)
PERMANENT
ONLINE
LOGGING;

ALTER DATABASE DEFAULT TABLESPACE "STARLIGHT_I";


