ALTER TABLE ADMIN_EMPLOYEES_ROLE_GROUPS 
 MODIFY (
  ID_ROLE_GROUPS NUMBER (8, 0)
 )
/
ALTER TABLE ADMIN_PROGRAMS 
 MODIFY (
  ID_ADMIN_PROGRAMS NUMBER (8, 0)
 )
/
ALTER TABLE ADMIN_PROGRAMS_BUTTONS 
 MODIFY (
  ID_PROGRAMS NUMBER (8, 0)
 )
/
ALTER TABLE ADMIN_PROGRAMS_ROLE_GROUPS 
 MODIFY (
  ID_PROGRAMS NUMBER (8, 0),
  ID_ROLE_GROUPS NUMBER (8, 0)
 )
/
ALTER TABLE ADMIN_ROLE_GROUPS 
 MODIFY (
  ID_ROLE_GROUPS NUMBER (8, 0)
 )
/
ALTER TABLE BOOKS_ADVERTISMENTS 
 MODIFY (
  ID_ADVERTISMENTS NUMBER (8, 0)
 )
/
ALTER TABLE BOOKS_CLIENT_TYPES 
 MODIFY (
  ID_CLIENT_TYPES NUMBER (8, 0)
 )
/
ALTER TABLE BOOKS_DEPARTMENTS 
 MODIFY (
  ID_DEPARTMENTS NUMBER (8, 0)
 )
/
ALTER TABLE BOOKS_REGIONS 
 MODIFY (
  ID_REGIONS NUMBER (8, 0)
 )
/
ALTER TABLE BUH_DOC 
 MODIFY (
  ID_DEPARTMENTS NUMBER (8, 0)
 )
/
ALTER TABLE BUTTONS_SET 
 MODIFY (
  ID_DEP NUMBER (8, 0)
 )
/
ALTER TABLE BUTTONS_SET_SALE 
 MODIFY (
  ID_DEP NUMBER (8, 0)
 )
/
ALTER TABLE CASH_TMP 
 MODIFY (
  OPERATION NUMBER (8, 0)
 )
/
ALTER TABLE CLIENT_DEBT 
 MODIFY (
  OPERATION NUMBER (8, 0)
 )
/
ALTER TABLE CLIENTS 
 MODIFY (
  TTYPE NUMBER (8, 0)
 )
/
ALTER TABLE CLIENTS_SALES 
 MODIFY (
  ID_DEPARTMENTS NUMBER (8, 0),
  ID NUMBER (8, 0)
 )
/
ALTER TABLE COUNTRIES 
 MODIFY (
  C_ID NUMBER (8, 0)
 )
/
ALTER TABLE CUSTOMS_WEIGHT 
 MODIFY (
  ID_DEP NUMBER (8, 0)
 )
/
ALTER TABLE DEF_TYPE_QUANT 
 MODIFY (
  ID_DEP NUMBER (8, 0)
 )
/
ALTER TABLE EMPLOYEES_DEPARTMENTS 
 MODIFY (
  ID_DEPARTMENTS NUMBER (8, 0)
 )
/
ALTER TABLE EMPLOYEES_JOB_TITLES 
 MODIFY (
  ID_JOB_TITLES NUMBER (8, 0)
 )
/
ALTER TABLE FITO_CATEGORY 
 MODIFY (
  ID_DEP NUMBER (8, 0)
 )
/
ALTER TABLE FLOWER_FITO_ALL_NAMES 
 MODIFY (
  ID_DEP NUMBER (8, 0)
 )
/
ALTER TABLE FLOWER_FITO_NAMES 
 MODIFY (
  ID_DEP NUMBER (8, 0)
 )
/

