-- Start of DDL Script for User UEGATE
-- Generated 08.03.2016 14:10:22 from CREATOR@STAR_NEW

CREATE USER UEGATE
IDENTIFIED BY "star_UEGATE"
DEFAULT TABLESPACE STARLIGHT_T
TEMPORARY TABLESPACE TEMP
/
GRANT UNLIMITED TABLESPACE TO uegate
/
GRANT CONNECT TO uegate
/
GRANT DBA TO uegate
/
GRANT RESOURCE TO uegate
/
ALTER USER uegate DEFAULT ROLE ALL
/


-- End of DDL Script for User UEGATE

