unit DataModule;

interface

uses
  SysUtils, Classes, DB, DBAccess, Ora, MemDS, DBTables, frxClass, frxDBSet, PI_Library_reg,
  Dialogs;

type
  TDM = class(TDataModule)
    STAR_DB: TOraSession;
    ForceQ: TOraQuery;
    InvoiceRegister: TOraQuery;
    InvoiceAsIs: TOraQuery;
    InvoiceRegister_DS: TDataSource;
    InvoiceAsIs_DS: TDataSource;
    InvoiceData: TOraQuery;
    InvoiceData_DS: TDataSource;
    SeekNomenclature: TOraQuery;
    FlowerTypes: TOraQuery;
    Nomenclature: TOraQuery;
    Nomenclature_DS: TDataSource;
    SelQ: TOraQuery;
    SeekRecognised: TOraQuery;
    OldDict: TQuery;
    OldDict_DS: TDataSource;
    DBOldDict: TDatabase;
    OldDictTITLE: TStringField;
    OldDictTITLERU: TStringField;
    OldDictFLOW: TSmallintField;
    OldDictMARK: TSmallintField;
    OldDictUNIT: TSmallintField;
    OldDictCODE: TStringField;
    OldDictHFL: TFloatField;
    FlowerTypesFT_ID: TFloatField;
    FlowerTypesF_TYPE: TStringField;
    FlowerTypesFT_MASK: TStringField;
    StorProc: TOraStoredProc;
    NomSpecs: TOraQuery;
    NomSpecs_DS: TOraDataSource;
    NomSpecsN_ID: TFloatField;
    NomSpecsHS_ID: TFloatField;
    NomSpecsSC_ID: TFloatField;
    NomSpecsHS_VAL: TStringField;
    NomSpecsORD: TFloatField;
    NomSpecsSPEC_CODE: TStringField;
    NomSpecsSPEC_NAME: TStringField;
    NomSpecsSPEC_HOL_NAME: TStringField;
    NomSpecsADDITION: TStringField;
    NomSpecsRUSSIAN_ADDITION: TStringField;
    NomSpecsNEED_TRANSLATION: TIntegerField;
    NomSpecsCONTENT_HOL: TStringField;
    NomSpecsCONTENT_RUS: TStringField;
    DataSource1: TDataSource;
    Nomenclature2: TOraQuery;
    Nomenclature2_DS: TDataSource;
    CDS_COUNTRY2: TOraQuery;
    CDS_COUNTRY2C_ID: TIntegerField;
    CDS_COUNTRY2COUNTRY: TStringField;
    DS_COUNTRY2: TOraDataSource;
    Nomenclature_one: TOraQuery;
    Nomenclature_one_DS: TDataSource;
    SelPrntPreview: TOraQuery;
    CDS_PRINT: TOraQuery;
    DS_PRINT: TDataSource;
    frx_print: TfrxReport;
    frx_print_db: TfrxDBDataset;
    frx_print_index: TfrxDBDataset;
    InvoiceRegisterINV_ID: TFloatField;
    InvoiceRegisterINV_DATE: TDateTimeField;
    InvoiceRegisterCOMMENTS: TStringField;
    InvoiceRegisterINV_SUM: TFloatField;
    InvoiceRegisterSENDED_TO_WAREHOUSE: TIntegerField;
    InvoiceRegisterWAREHOUSE_SENDED_DATE: TDateTimeField;
    InvoiceRegisterSUPPLIER_DATE: TDateTimeField;
    InvoiceRegisterSUPPLIER_NUMBER: TStringField;
    InvoiceRegisterIPP_ID: TFloatField;
    InvoiceRegisterID_DEPARTMENTS: TFloatField;
    InvoiceRegisterINV_MINUS: TIntegerField;
    InvoiceRegisterIN_FILE: TStringField;
    InvoiceRegisterIS_FILE: TFloatField;
    InvoiceRegisterIS_MINUS: TFloatField;
    InvoiceRegisterINVOICE_TITLE: TStringField;
    InvoiceRegisterS_ID_DEFAULT: TFloatField;
    InvoiceRegisterC_ID_DEFAULT: TFloatField;
    InvoiceRegisterMINUS_INV_ID: TFloatField;
    InvoiceRegisterS_NAME_RU: TStringField;
    InvoiceRegisterIPP_COMMENT: TStringField;
    InvoiceRegisterPRICE: TFloatField;
    InvoiceRegisterPRICE_DONE: TFloatField;
    InvoiceRegisterAS_IS_POS: TFloatField;
    InvoiceRegisterREADY_POS: TFloatField;
    InvoiceRegisterTOTAL_SUM_AS_IS: TFloatField;
    InvoiceRegisterTO_BE_POS: TFloatField;
    InvoiceRegisterTOTAL_SUM_TO_BE: TFloatField;
    InvoiceRegisterTOTAL_SUM_FROM_MINUS: TFloatField;
    InvoiceRegisterD_CHECK: TFloatField;
    InvoiceRegisterINV_ID_: TFloatField;
    InvoiceRegisterPAST_NUM: TFloatField;
    InvoiceRegisterPROCENT_D: TFloatField;
    InvoiceRegisterID_OFFICE: TIntegerField;
    InvoiceRegisterBRIEF: TStringField;
    InvoiceRegisterOFFICE: TStringField;
    InvoiceRegisterIARCHIVE: TIntegerField;
    SaveDialog: TSaveDialog;
    SelPrntPreviewN_ID: TFloatField;
    SelPrntPreviewTITLE: TStringField;
    SelPrntPreviewPRICE: TFloatField;
    SelPrntPreviewCODE: TFloatField;
    SelPrntPreviewH_CODE: TStringField;
    SelPrntPreviewCOLOUR: TStringField;
    SelPrntPreviewF_NAME_RU: TStringField;
    SelPrntPreviewCOUNTRY: TStringField;
    SelPrntPreviewRUS_MARKS: TStringField;
    SelPrntPreviewBAR_CODE: TStringField;
    SelPrntPreviewPRINT_CODE: TFloatField;
    SelPrntPreviewPACK_PRICE: TFloatField;
    SelPrntPreviewINVOICE_ID: TFloatField;
    SelPrntPreviewPACKQ: TIntegerField;
    SelPrntPreviewTROLLEY: TFloatField;
    SelPrntPreviewTRUCK: TFloatField;
    SelPrntPreviewSRC_TROLLEY: TStringField;
    SelPrntPreviewORDER_NUMBER: TFloatField;
    SelPrntPreviewTROLLEY_CALC: TFloatField;
    Nomenclature_oneCOMPILED_NAME: TStringField;
    Nomenclature_oneFULL_NAME: TStringField;
    Nomenclature_oneF_NAME: TStringField;
    Nomenclature_oneF_NAME_RU: TStringField;
    Nomenclature_oneF_SUB_TYPE: TStringField;
    Nomenclature_oneF_TYPE: TStringField;
    Nomenclature_oneN_ID: TFloatField;
    Nomenclature_oneFN_ID: TFloatField;
    Nomenclature_oneFT_ID: TFloatField;
    Nomenclature_oneFST_ID: TFloatField;
    Nomenclature_oneS_ID: TFloatField;
    Nomenclature_oneC_ID: TFloatField;
    Nomenclature_oneCOL_ID: TFloatField;
    Nomenclature_oneH_CODE: TStringField;
    Nomenclature_oneH_NAME: TStringField;
    Nomenclature_oneCODE: TFloatField;
    Nomenclature_oneBAR_CODE: TStringField;
    Nomenclature_oneLEN: TIntegerField;
    Nomenclature_onePACK: TIntegerField;
    Nomenclature_oneVBN: TIntegerField;
    Nomenclature_oneHOL_TYPE: TStringField;
    Nomenclature_oneWEIGHT: TFloatField;
    Nomenclature_oneWEIGHTDRY: TFloatField;
    Nomenclature_oneS_NAME_RU: TStringField;
    Nomenclature_oneCOLOUR: TStringField;
    Nomenclature_oneCOUNTRY: TStringField;
    Nomenclature_oneTYPE_SUBTYPE: TStringField;
    Nomenclature_oneF_NAMES: TStringField;
    Nomenclature_oneCUST_COEF: TFloatField;
    Nomenclature_oneDIAMETER: TFloatField;
    Nomenclature_oneHT_ID: TFloatField;
    Nomenclature_oneIS_PHOTO: TFloatField;
    Nomenclature_onePHOTO: TStringField;
    Nomenclature_oneREMARKS: TStringField;
    Nomenclature_oneRUS_MARKS: TStringField;
    Nomenclature_oneCOMPILED_NAME_OTDEL: TStringField;
    Nomenclature_oneID_OFFICE: TIntegerField;
    Nomenclature_oneTNVED: TStringField;
    Nomenclature2COMPILED_NAME: TStringField;
    Nomenclature2FULL_NAME: TStringField;
    Nomenclature2F_NAME: TStringField;
    Nomenclature2F_NAME_RU: TStringField;
    Nomenclature2F_SUB_TYPE: TStringField;
    Nomenclature2F_TYPE: TStringField;
    Nomenclature2N_ID: TFloatField;
    Nomenclature2FN_ID: TFloatField;
    Nomenclature2FT_ID: TFloatField;
    Nomenclature2FST_ID: TFloatField;
    Nomenclature2S_ID: TFloatField;
    Nomenclature2C_ID: TFloatField;
    Nomenclature2COL_ID: TFloatField;
    Nomenclature2H_CODE: TStringField;
    Nomenclature2H_NAME: TStringField;
    Nomenclature2CODE: TFloatField;
    Nomenclature2BAR_CODE: TStringField;
    Nomenclature2LEN: TIntegerField;
    Nomenclature2PACK: TIntegerField;
    Nomenclature2VBN: TIntegerField;
    Nomenclature2HOL_TYPE: TStringField;
    Nomenclature2WEIGHT: TFloatField;
    Nomenclature2WEIGHTDRY: TFloatField;
    Nomenclature2S_NAME_RU: TStringField;
    Nomenclature2COLOUR: TStringField;
    Nomenclature2COUNTRY: TStringField;
    Nomenclature2TYPE_SUBTYPE: TStringField;
    Nomenclature2F_NAMES: TStringField;
    Nomenclature2CUST_COEF: TFloatField;
    Nomenclature2DIAMETER: TFloatField;
    Nomenclature2HT_ID: TFloatField;
    Nomenclature2IS_PHOTO: TFloatField;
    Nomenclature2PHOTO: TStringField;
    Nomenclature2REMARKS: TStringField;
    Nomenclature2RUS_MARKS: TStringField;
    Nomenclature2COMPILED_NAME_OTDEL: TStringField;
    Nomenclature2UNITS: TFloatField;
    Nomenclature2ID_OFFICE: TIntegerField;
    Nomenclature2TNVED: TStringField;
    NomenclatureCOMPILED_NAME: TStringField;
    NomenclatureFULL_NAME: TStringField;
    NomenclatureF_NAME: TStringField;
    NomenclatureF_NAME_RU: TStringField;
    NomenclatureF_SUB_TYPE: TStringField;
    NomenclatureF_TYPE: TStringField;
    NomenclatureN_ID: TFloatField;
    NomenclatureFN_ID: TFloatField;
    NomenclatureFT_ID: TFloatField;
    NomenclatureFST_ID: TFloatField;
    NomenclatureS_ID: TFloatField;
    NomenclatureC_ID: TFloatField;
    NomenclatureCOL_ID: TFloatField;
    NomenclatureH_CODE: TStringField;
    NomenclatureH_NAME: TStringField;
    NomenclatureCODE: TFloatField;
    NomenclatureBAR_CODE: TStringField;
    NomenclatureLEN: TIntegerField;
    NomenclaturePACK: TIntegerField;
    NomenclatureVBN: TIntegerField;
    NomenclatureHOL_TYPE: TStringField;
    NomenclatureWEIGHT: TFloatField;
    NomenclatureWEIGHTDRY: TFloatField;
    NomenclatureS_NAME_RU: TStringField;
    NomenclatureCOLOUR: TStringField;
    NomenclatureCOUNTRY: TStringField;
    NomenclatureTYPE_SUBTYPE: TStringField;
    NomenclatureF_NAMES: TStringField;
    NomenclatureCUST_COEF: TFloatField;
    NomenclaturePRICE: TFloatField;
    NomenclaturePRICE_DATE: TDateTimeField;
    NomenclatureDIAMETER: TFloatField;
    NomenclatureHT_ID: TFloatField;
    NomenclatureIS_PHOTO: TFloatField;
    NomenclaturePHOTO: TStringField;
    NomenclatureREMARKS: TStringField;
    NomenclatureCOMPILED_NAME_POT: TStringField;
    NomenclatureQUANTITY: TFloatField;
    NomenclatureCOMPILED_NAME_OTDEL: TStringField;
    NomenclatureID_OFFICE: TIntegerField;
    NomenclatureTNVED: TStringField;
    CDS_PRINTN_ID: TFloatField;
    CDS_PRINTUNITS: TFloatField;
    CDS_PRINTF_NAME: TStringField;
    CDS_PRINTF_NAME_RU: TStringField;
    CDS_PRINTCOLOUR: TStringField;
    CDS_PRINTCOUNTRY: TStringField;
    CDS_PRINTS_NAME_RU: TStringField;
    CDS_PRINTRUS_MARKS: TStringField;
    CDS_PRINTH_CODE: TStringField;
    CDS_PRINTBAR_CODE: TStringField;
    CDS_PRINTTROLLEY: TFloatField;
    CDS_PRINTTRUCK: TFloatField;
    CDS_PRINTSRC_TROLLEY: TStringField;
    CDS_PRINTTROLLEY_CALC: TFloatField;
    CDS_PRINTF_TYPE: TStringField;
    CDS_PRINTF_SUB_TYPE: TStringField;
    Nomenclature_oneUNITS: TFloatField;
    InvoiceRegisterCOUNTRY_GTD: TIntegerField;
    NomenclatureNOM_NEW: TIntegerField;
    NomenclatureNOM_START: TIntegerField;
    NomenclatureNOM_END: TIntegerField;
    Nomenclature2NOM_NEW: TIntegerField;
    Nomenclature2NOM_START: TIntegerField;
    Nomenclature2NOM_END: TIntegerField;
    Nomenclature_oneNOM_NEW: TIntegerField;
    Nomenclature_oneNOM_START: TIntegerField;
    Nomenclature_oneNOM_END: TIntegerField;
    Nomenclature_oneHOL_COLOR: TStringField;
    Nomenclature2HOL_COLOR: TStringField;
    Nomenclature_oneNAME_CODE: TStringField;
    Nomenclature2NAME_CODE: TStringField;
    NomenclatureHOL_COLOR: TStringField;
    NomenclatureNAME_CODE: TStringField;
    Nomenclature2HOL_PACK: TIntegerField;
    Nomenclature_oneHOL_PACK: TIntegerField;
    NomenclatureHOL_PACK: TIntegerField;
    NomenclatureNSI_NAME: TStringField;
    qStore: TQuery;
    dStore: TDataSource;
    qStoreA: TStringField;
    qStoreB: TStringField;
    qStoreC: TStringField;
    inv_table: TTable;
    inv_table_ds: TDataSource;
    inv_tableA: TStringField;
    inv_tableB: TStringField;
    inv_tableC: TStringField;
    SelQ2: TOraQuery;
    InvoiceDataD_CHECK: TFloatField;
    InvoiceDataINV_ID: TFloatField;
    InvoiceDataN_ID: TFloatField;
    InvoiceDataUNITS: TFloatField;
    InvoiceDataPRICE_PER_UNIT: TFloatField;
    InvoiceDataTOTAL_SUM: TFloatField;
    InvoiceDataAMOUNT_IN_THE_PACK: TFloatField;
    InvoiceDataINVOICE_DATA_ID: TFloatField;
    InvoiceDataINVOICE_DATA_AS_IS_ID: TFloatField;
    InvoiceDataFULL_NAME: TStringField;
    InvoiceDataF_NAME: TStringField;
    InvoiceDataF_NAME_RU: TStringField;
    InvoiceDataLEN: TIntegerField;
    InvoiceDataCOLOUR: TStringField;
    InvoiceDataCOUNTRY: TStringField;
    InvoiceDataS_NAME_RU: TStringField;
    InvoiceDataINV_MARKS: TStringField;
    InvoiceDataRUS_MARKS: TStringField;
    InvoiceDataDIAMETER: TFloatField;
    InvoiceDataFT_ID: TFloatField;
    InvoiceDataF_TYPE: TStringField;
    InvoiceDataFST_ID: TFloatField;
    InvoiceDataF_SUB_TYPE: TStringField;
    InvoiceDataCUST_COEF: TFloatField;
    InvoiceDataGTD: TStringField;
    InvoiceDataH_CODE: TStringField;
    InvoiceDataSENDED_TO_WAREHOUSE: TIntegerField;
    InvoiceDataPACK: TFloatField;
    InvoiceDataHOL_PACK: TIntegerField;
    InvoiceDataSTORNED_DATA: TIntegerField;
    InvoiceDataSTORNED_TEXT: TStringField;
    InvoiceDataREMARKS: TStringField;
    InvoiceDataCODE: TFloatField;
    InvoiceDataBAR_CODE: TStringField;
    InvoiceDataIS_PHOTO: TFloatField;
    InvoiceDataPHOTO: TStringField;
    InvoiceDataNN: TFloatField;
    InvoiceDataTRUCK: TIntegerField;
    InvoiceDataTROLLEY: TFloatField;
    InvoiceDataSRC_TROLLEY: TStringField;
    InvoiceDataCLIENT: TStringField;
    InvoiceDataTROLLEY_CALC: TFloatField;
    InvoiceDataUNITS_PRINT: TFloatField;
    InvoiceDataCOMPILED_NAME_OTDEL: TStringField;
    InvoiceDataH_NAME: TStringField;
    InvoiceDataNOPRINT: TIntegerField;
    InvoiceDataNOTUSE: TIntegerField;
    InvoiceDataFN_ID: TFloatField;
    InvoiceDataC_ID: TFloatField;
    InvoiceDataS_ID: TFloatField;
    InvoiceDataCOL_ID: TFloatField;
    InvoiceDataHT_ID: TFloatField;
    InvoiceDataWEIGHT: TFloatField;
    InvoiceDataWEIGHTDRY: TFloatField;
    InvoiceDataVBN: TIntegerField;
    InvoiceDataTNVED: TStringField;
    InvoiceDataHOL_TYPE: TStringField;
    InvoiceDataGTD_COUNTRY: TIntegerField;
    InvoiceDataGTD_COUNTRY_NAME: TStringField;
    InvoiceDataNOM_NEW: TIntegerField;
    InvoiceDataNOM_START: TIntegerField;
    InvoiceDataNOM_END: TIntegerField;
    InvoiceDataNOM_ADD: TIntegerField;
    InvoiceDataNOM_SPECIAL: TIntegerField;
    InvoiceDataPARENT: TFloatField;
    InvoiceDataHOL_COLOR: TStringField;
    InvoiceDataNAME_CODE: TStringField;
    InvoiceDataNSI_NAME: TStringField;
    InvoiceAsIsINV_ID: TFloatField;
    InvoiceAsIsORDER_NUMBER: TFloatField;
    InvoiceAsIsORDER_MARKNAME: TStringField;
    InvoiceAsIsPACKING_MARKS: TStringField;
    InvoiceAsIsPACKING_CODE: TStringField;
    InvoiceAsIsDESCRIPTION: TStringField;
    InvoiceAsIsUNITS: TFloatField;
    InvoiceAsIsSKU: TStringField;
    InvoiceAsIsAMOUNT_IN_THE_PACK: TFloatField;
    InvoiceAsIsINVOICE_DATA_AS_IS_ID: TFloatField;
    InvoiceAsIsHOL_COLOUR: TStringField;
    InvoiceAsIsHOL_SUB_TYPE: TStringField;
    InvoiceAsIsMARKS_CONTENT: TStringField;
    InvoiceAsIsMARKS_NAMES: TStringField;
    InvoiceAsIsSHORT_CODE: TStringField;
    InvoiceAsIsSHORT_NAME: TStringField;
    InvoiceAsIsRECOGNISED: TIntegerField;
    InvoiceAsIsBAR_CODE: TStringField;
    InvoiceAsIsTRANSLATION: TStringField;
    InvoiceAsIsAMOUNT_PER_UNIT: TFloatField;
    InvoiceAsIsTOTAL_AMOUNT: TFloatField;
    InvoiceAsIsREMARKS: TStringField;
    InvoiceAsIsSPEC_LENGTH: TFloatField;
    InvoiceAsIsSPEC_HEADS: TStringField;
    InvoiceAsIsSPEC_HEADS_SHRUB: TStringField;
    InvoiceAsIsSPEC_VD2: TStringField;
    InvoiceAsIsSPEC_WIDTH: TFloatField;
    InvoiceAsIsSPEC_HIGHT: TFloatField;
    InvoiceAsIsTROLLEY: TFloatField;
    InvoiceAsIsTRUCK: TIntegerField;
    InvoiceAsIsCLIENT: TStringField;
    InvoiceAsIsSRC_TROLLEY: TStringField;
    InvoiceAsIsID_OFFICE: TIntegerField;
    InvoiceAsIsDATE_CHANGE: TDateTimeField;
    InvoiceAsIsVOLUME: TFloatField;
    InvoiceAsIsVOLDRY: TFloatField;
    InvoiceAsIsNOM_NEW: TIntegerField;
    InvoiceAsIsNOM_START: TIntegerField;
    InvoiceAsIsCOUNTRY_: TStringField;
    InvoiceAsIsNOM_END: TIntegerField;
    InvoiceAsIsNOM_ADD: TIntegerField;
    InvoiceAsIsNOM_SPECIAL: TIntegerField;
    InvoiceAsIsNOM_PACK: TIntegerField;
    InvoiceAsIsNOM_PACK_HOL: TIntegerField;
    InvoiceAsIsREPLACEMENT: TStringField;
    procedure STAR_DBBeforeConnect(Sender: TObject);
    procedure NomenclatureBeforeOpen(DataSet: TDataSet);
    procedure Nomenclature2BeforeOpen(DataSet: TDataSet);
    procedure Nomenclature2BeforeRefresh(DataSet: TDataSet);
    procedure Nomenclature_oneBeforeOpen(DataSet: TDataSet);
    procedure DataModuleCreate(Sender: TObject);
    procedure InvoiceRegisterBeforeOpen(DataSet: TDataSet);
  private
    { Private declarations }
  public
    id_office: integer;
    n_id_: integer;
    def_suplier: integer;
    { Public declarations }
  end;

var
  DM: TDM;

implementation

uses Globals, RecogniserU;

{$R *.dfm}

procedure TDM.STAR_DBBeforeConnect(Sender: TObject);
begin
  TOraSession(Sender).Server := ora_db_path;
  TOraSession(Sender).Username := username;
  TOraSession(Sender).Password := password;
end;

procedure TDM.NomenclatureBeforeOpen(DataSet: TDataSet);
begin
  Nomenclature.ParamByName('ID_DEPARTMENTS_').Value := CUR_DEPT_ID;
  Nomenclature.ParamByName('v_office').AsInteger    := id_office;
end;

procedure TDM.DataModuleCreate(Sender: TObject);
begin
  STAR_DB.Connect;
  id_office := GetOfficeID;
end;

procedure TDM.InvoiceRegisterBeforeOpen(DataSet: TDataSet);
begin
  InvoiceRegister.ParamByName('v_office').AsInteger    := id_office;
end;

procedure TDM.Nomenclature2BeforeOpen(DataSet: TDataSet);
begin
  Nomenclature2.ParamByName('ID_DEPARTMENTS_').Value := CUR_DEPT_ID;
  Nomenclature2.ParamByName('n_id_').Value := 0;
  Nomenclature2.ParamByName('vSupplier').Value := def_suplier;
end;

procedure TDM.Nomenclature2BeforeRefresh(DataSet: TDataSet);
begin
  Nomenclature2.ParamByName('ID_DEPARTMENTS_').Value := CUR_DEPT_ID;
  Nomenclature2.ParamByName('n_id_').Value := n_id_;
  Nomenclature2.ParamByName('vSupplier').Value := def_suplier;
end;

procedure TDM.Nomenclature_oneBeforeOpen(DataSet: TDataSet);
begin
  Nomenclature_one.ParamByName('ID_DEPARTMENTS_').Value := CUR_DEPT_ID;
//  Nomenclature_one.ParamByName('n_id_').Value := n_id_;
end;


end.
