    SELECT p.PREP_DIST_ID, p.DIST_IND_ID, p.N_ID, p.INVOICE_DATA_ID, p.ID_STORE_MAIN, p.TOTAL_QUANTITY, p.LEFT_QUANTITY
    FROM PREP_DIST_VIEW p
        WHERE  p.DIST_IND_ID = 344
            AND p.LEFT_QUANTITY > 0
            AND p.N_ID = 10062723
         ORDER BY p.INVOICE_DATA_ID, p.ID_STORE_MAIN;

