INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(163,1573,'gold/yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(166,2806,'orange/green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(165,2804,'burgundy/green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(182,2658,'Gl/Zwart');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(185,0,'aubergine');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(187,2831,'cyclamen');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(189,2680,'metallic silver');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(190,2706,'white-gold');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(191,2678,'bordo');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(192,1573,'green-white');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(243,2907,'copper-gold');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(244,2908,'burgundy-gold');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(246,2913,'ivory matt');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(248,2914,'taupe matt');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(250,2820,'metallic');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(258,1668,'d.brown');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(260,1886,'black');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(262,1370,'ivory');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(267,1386,'taupe');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(268,1670,'grey');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(270,2750,'beige');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(332,2935,'Bronse W/GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(333,2936,'Copper W/GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(334,2922,'gold W/GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(335,2937,'silver W/GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(336,2653,'purple ');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(337,2712,'olive green ');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(338,2938,'white/brown ');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(339,2758,'red/brown ');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(340,2939,'d.pink with GLITER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(341,2940,'dark gray');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(342,2675,'dark grin');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(343,2651,'Bronse');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(344,2941,'Claret with GLITER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(345,2942,'Lilac with GLITER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(346,2932,'orange W/GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(347,2933,'l.GREEN W/GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(348,2943,'GREEN W/silver GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(349,1883,'light brown ');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(350,2944,'dark purple W/GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(351,2917,'brown W/GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(352,2942,'Lilac W/GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(353,2726,'Cherry');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(354,1362,'yellow ');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(477,0,'Gemengd');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(478,1819,'Twee kleurig');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(136,2734,'Peony');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(146,2776,'black/goldluster');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(147,2780,'Cherry-gold');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(148,2782,'Gold bronze');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(149,2784,'Gold-luster');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(150,2786,'Lilac luster');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(151,2788,'Olive-gold');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(152,2790,'Ruby/gold');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(153,2792,'Savana-gold');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(154,2794,'white/goldluster');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(167,2653,'mauve');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(171,1440,'nile');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(172,2675,'moss-green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(184,2828,'purple/lilac');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(193,2851,'lotus');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(194,2853,'aqua');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(195,2855,'glow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(196,2857,'lemonade');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(197,1396,'juicy orange');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(198,2859,'viola');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(199,0,'chartreuse');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(200,1362,'sunflower');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(201,1493,'insignia blue');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(202,2843,'light-blue');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(203,2746,'limone');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(206,1355,'01');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(207,1360,'30');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(208,2678,'38');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(210,1639,'Unknown');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(211,2169,'Blue/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(212,2890,'NA');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(213,2240,'Cream/Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(214,1639,'White/Purple');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(239,2901,'Peach/Green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(240,2902,'Red/Purple');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(241,0,'Red/Orange');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(358,2951,'GOUD/BRUIN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(359,2655,'GOUD');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(360,2655,'MARMER EUCALYPTUS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(361,2701,'GROEN/GOUD GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(363,1573,'ZACHT GROEN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(364,2837,'GOUD/GROEN M.GLIT');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(365,2680,'GROEN/ZILVER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(366,2837,'GOUD/GROEN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(367,2837,'BRUIN/GROEN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(368,2837,'GROEN/GOUD');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(369,1573,'GROEN/LAURIER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(370,1668,'D.BRUIN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(371,2960,'L.GRIJ/ANTHR/GR.BL');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(372,2680,'L.GRIJS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(373,2961,'WIT M.ZWARTE GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(374,2962,'CLEAR SNEEUW+IRR.GLITT');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(377,2963,'CLEAR/GRIJS/ZWART');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(378,2964,'WIT/GRIJS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(379,2965,'CLEAR/ZWART+CIRKEL');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(380,2966,'ZILVER OLIJF/DIAMANT');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(381,2680,'ZILVER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(382,1355,'WIT');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(384,2712,'OLIJF');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(386,2964,'WIT/ZILVER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(387,2937,'ZILVER GL');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(393,1670,'GRIJS/L.GRIJS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(391,2929,'WIT+GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(392,2663,'CLEAR');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(394,1886,'ZWART');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(396,2700,'GRIJS/ZILVER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(397,2929,'WIT/GL');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(398,2696,'ZWART/WIT GLI');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(399,1670,'DIAMANT GRIJS/L.GRIJS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(400,1670,'GRIJS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(401,2700,'ZILVER/D.GRIJS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(402,2700,'D.GRIJS/ZILVER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(403,2948,'ZWART/ZILVER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(404,2964,'ZILVER/WIT');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(405,2700,'ZILVER/DONKER GRIJS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(406,2663,'TINSEL CLEAR');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(408,2970,'ZILV/GR.BL');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(409,2680,'TINSEL ZILVER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(410,1573,'Z.GROEN/EUCALYPTUS/LAUR');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(411,1573,'EUCALYPTUS/ZACHT GROEN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(412,2782,'GOUD BRUIN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(413,2837,'GROEN GOUD GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(414,1573,'GROEN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(415,2922,'GOUD M.GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(416,1908,'MAIS/GROEN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(417,2971,'GOUD/ZILV');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(418,1565,'BRUIN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(419,1600,'LAURIER MET WITTE TAK');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(420,1573,'GROEN M.TAK');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(421,1573,'EUCAL/GROEN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(422,1362,'MAIS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(423,1362,'MAIS/CHAMP');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(424,2698,'GROEN/MAIS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(425,2837,'GROENGOUD');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(426,1908,'TINSEL MAIS/GROEN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(427,1908,'TINSEL CL.EUCALYP/MAIS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(428,2869,'TINSEL DE LUXE MAIS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(429,2916,'TINSEL HULSTBLAD GROEN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(430,1908,'TINSEL GROEN/MAIS');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(431,1908,'TINSEL MAIS/GROEN/CHAM');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(447,2107,'Red/Cream');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(452,1413,'Light pink/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(453,1413,'Dark Pink/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(472,2873,'Ivory/Peach');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(473,2738,'Cream/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(175,2818,'cerise');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(137,2770,'Dark Peach');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(164,2802,'autumn');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(186,2831,'Cyclaam');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(205,1668,'25');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(236,2897,'Cream/Purple');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(242,2906,'Lavender/Light Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(278,1440,'L.GREEN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(279,2919,'GOLD/SILVER GLIT');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(280,2920,'LILAC/SILVER GLI');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(281,2920,'LILAC/SILV.GL');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(282,2907,'COPPER /GOLD');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(283,1493,'BLUE');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(285,2921,'BLUE/PINK');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(286,2922,'GOLD GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(287,1744,'D.RED');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(465,1351,'Hot Pink/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(469,1418,'Hot pink/Dark Purple');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(1,2660,'Red/orange/yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(2,2661,'Fuchsia');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(3,2662,'Terra');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(4,2684,'Red/silver');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(5,2708,'Green/brown');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(237,2899,'Burgundy/Black');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(7,1351,'Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(10,1362,'Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(11,1366,'White/Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(13,1372,'Different colors');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(14,1374,'Light Yellow/Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(15,1377,'Peach/Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(16,1385,'Cream/Peach');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(18,1389,'Peach');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(19,1390,'Hot Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(20,1391,'Lavender');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(21,1392,'Peach/Cream');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(22,1396,'Orange');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(23,1408,'Brown/Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(24,1413,'Pink/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(25,1414,'Pink/Cream');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(26,1417,'Golden Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(27,1418,'Dark Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(28,1423,'Burgundy');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(29,1424,'Light Pink/Dark Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(30,1440,'Light Green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(31,1441,'Purple');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(32,1444,'Light Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(33,1449,'Orange/Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(35,1501,'Yellow/Orange');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(36,1503,'Dark Orange');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(37,1526,'Black/Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(38,1528,'Red/Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(39,1542,'Red/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(40,1554,'Light Orange');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(42,1569,'Light Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(43,1573,'Green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(44,1595,'Mixed');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(45,1599,'Green/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(46,1600,'White/Green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(47,1601,'Green/Purple');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(48,1620,'Peach/Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(321,2928,'dull red');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(50,1646,'Others');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(51,1655,'Dark Blue');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(52,1660,'Light BLue');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(53,1662,'Red/Green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(54,1665,'Green/Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(55,1668,'Dark Brown');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(57,1679,'Light Red');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(58,1712,'Dark Purple');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(59,1744,'Dark Red');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(60,1782,'Dark Orange/Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(61,1783,'Mixed in bunch');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(62,1785,'Violet');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(63,1808,'Light Orange/Dark Orange');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(64,1819,'Two-tone');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(65,1835,'White/Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(66,1871,'Purple/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(67,1882,'Pink/Green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(68,1883,'Light Brown');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(70,1908,'Yellow/Green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(71,1961,'Orange/Black');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(72,1971,'White/Black');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(73,1975,'Mixed in box');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(74,2022,'Light Red/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(75,2032,'Blue/Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(76,2033,'Asst. in box');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(77,2047,'Yellow/Black Center');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(78,2094,'White/Red');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(79,2107,'Cream/Red');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(80,2113,'Yellow/Cream');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(81,2117,'Lavender/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(82,2169,'White/Blue');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(83,2180,'Mixed in pack');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(84,2221,'Ivory/Red');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(86,2242,'Light Purple');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(87,2269,'Orange/Brown');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(88,2300,'Brown/Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(89,2548,'Pink/Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(90,2676,'D. yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(91,2677,'Salmon');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(92,2696,'Black/white');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(93,2663,'Transparent');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(94,2664,'Lime');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(95,2665,'Orange/white');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(96,2666,'Natural');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(97,2683,'Wine red');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(98,2702,'Ochre');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(99,2703,'Pearl');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(100,2706,'White/gold');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(101,2667,'Forestgreen');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(102,2668,'Green/green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(103,2669,'Red/pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(104,2670,'Lilac/lilac');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(105,2648,'applegreen');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(106,2649,'Platinum');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(107,2650,'Black mat');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(108,2651,'Brons');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(109,2652,'Silver black');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(110,2653,'Lilac');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(111,2654,'Apple green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(113,2656,'Caramel');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(114,2657,'Gold/red/lila');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(115,2658,'Gold/black');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(116,2672,'Green/orange');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(117,2673,'Gold/red');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(118,2674,'Sunflowers');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(119,2675,'D.green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(120,2678,'Bordeaux');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(121,2679,'Copper');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(123,2681,'Mango');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(124,2682,'-');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(125,2697,'Assorted');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(126,2698,'Green/yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(127,2699,'Green/red');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(128,2700,'Grey/silver');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(129,2701,'Green/gold');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(130,2704,'Green/burgundy');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(131,2705,'Green/violet');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(132,2707,'Gold/Burgundy');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(238,2900,'Purple/Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(322,1355,'white ');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(323,2651,'bronze');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(157,2240,'cream-pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(158,2240,'Cream/Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(159,1595,'Mix');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(162,2798,'Rust');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(173,2816,'Perl');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(174,2712,'olive');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(324,2929,'white with GLITER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(178,1493,'Blue Moon');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(179,2822,'Robijn/Staalblauw luster');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(180,2790,'Robijn/goud luster');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(181,2780,'Cherry Gold');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(183,2790,'Robljn/goud luster');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(325,2918,'red with GLITER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(326,2930,'purple with GLITER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(327,2922,'gold with GLITER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(328,2931,'black with GLITER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(329,2932,'orange  with GLITER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(330,2933,'light green with GLITER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(331,2934,'pink with GLITER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(357,1351,'Pink/Black Center');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(462,1423,'Burgundy/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(471,2873,'Ivory/Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(134,2732,'Mint');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(135,2712,'Olijv');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(215,1639,'Burgundy/Purple');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(216,1360,'Orange/Red');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(217,1639,'Red/Brown');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(160,2724,'Bronse/Gold');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(161,2796,'Mustard');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(168,1351,'rose');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(169,1386,'creme');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(170,2680,'slver');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(218,1639,'Yellow/White');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(219,1639,'Green/Cream');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(220,2891,'Cream/Black Center');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(221,1639,'White/Orange');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(222,1639,'Dark Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(223,1639,'Brown/Green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(224,1639,'Pink/Red');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(225,1639,'Green/Grey');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(226,1639,'Light Salmon');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(227,1639,'Yellow/Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(228,1639,'Pink/Orange');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(229,1639,'Yellow/Red');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(230,2892,'Cream/Orange');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(231,2894,'Red/Black Center');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(232,2895,'Dark Orange/Black Center');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(233,2896,'Orange/Yellow/Black center');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(234,0,'Orange/Black Center');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(235,1971,'White/Black Center');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(272,2916,'GREEN W/GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(273,2917,'BROWN W/GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(275,2918,'RED W/GLITTER');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(276,1503,'D.ORANGE');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(277,1418,'D.PINK');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(296,1360,'RED');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(298,1386,'CREAM');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(299,2655,'GOLD');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(303,1883,'L.BROWN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(305,2680,'d.silver');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(306,1660,'l.blue');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(307,1423,'burgondy');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(308,2663,'transp');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(309,1712,'d.purple');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(311,2680,'silver');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(312,1565,'brown');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(313,2915,'silver/anthracite/bronze');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(316,2927,'orange/gold/brown');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(320,1355,'white');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(356,1639,'Dark Pink/Light Pink');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(390,1600,'WIT/GROEN');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(395,2968,'OLIJF ZILVER/WIT');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(433,1366,'Purple/Cream');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(435,1414,'Dark Purple/Golden Yellow');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(460,1355,'White/Lavender');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(466,1396,'Orange/Peach');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(474,2675,'Dark Green');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(475,1389,'Peach/Black Center');
INSERT INTO h_colours (H_COL_ID,COL_ID,HOL_COLOUR) 
VALUES(479,3020,'brushed laquered');
