INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(160,'Служебная',NULL,0,61);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(159,'Азалии',NULL,13,61);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(154,'Кашпо',NULL,0,121);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(153,'Горшечные растения',NULL,0,121);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(115,'Роза Эквадор',NULL,2,62);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(2,'Хризантема','CHR',3,62);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(3,'Лилия','LI',7,62);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(0,'Не указано',NULL,0,62);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(82,'N/A',NULL,0,62);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(137,'Цветущие растения',NULL,0,61);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(138,'Зеленые (нецветущие) растения',NULL,0,61);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(139,'Растения открытого грунта',NULL,0,61);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(140,'Роза',NULL,0,61);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(114,'Тюльпан',NULL,5,62);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(106,'Гвоздика',NULL,6,62);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(109,'Другие цветы',NULL,5,62);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(110,'Зелень',NULL,4,62);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(111,'Орхидея',NULL,4,62);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(112,'Гербера',NULL,4,62);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(113,'Роза Голландия',NULL,1,62);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(146,'Аксессуары для флористов',NULL,0,121);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(147,'Искусственные цветы',NULL,0,121);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(148,'Новогодняя коллекция',NULL,0,121);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(149,'Оазис',NULL,0,121);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(150,'Предметы для оформления интерьера',NULL,0,121);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(151,'Сухоцветы',NULL,0,121);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(152,'Неразнесенное',NULL,0,121);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(155,'Кашпо',NULL,0,61);
INSERT INTO flower_types (FT_ID,F_TYPE,FT_MASK,HT_ID,ID_DEPARTMENTS) 
VALUES(158,'Горшечные растения',NULL,0,61);
